version: '3'

services:
  redis:
    image: redis:alpine
    restart: always

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql/data:Z
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_DATABASE:${MYSQL_DATABASE}
      - MYSQL_USER:${MYSQL_USER}
    restart: unless-stopped
  
  # postgres:
  #   image: postgres:alpine
  #   restart: always
  #   volumes:
  #     - db:/var/lib/postgresql/data:Z
  #   environment:
  #     - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=nextcloud
  #     - POSTGRES_USER=nextcloud

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
      - 8080:80
    networks:
      - nextcloud_network
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html/data
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped

volumes:
  nextcloud:
  db:
networks:
  nextcloud_network:
