version: '3'

services:
  redis:
    image: redis:alpine
    restart: always

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
      - "8080:80"
    networks:
      - nextcloud_network
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped

volumes:
  nextcloud:
  db:
networks:
  nextcloud_network:
